### ISSUE TITLE
Crash when resizing during training

### ISSUE THREAD

**Issue by sharived** [sowson/darknet#3]
I have tried training a few different yolov3 models without any success.  When trying to train VOC or tiny coco model I crash when the resizing is done in train_detector.  The crash in in opencl_push_int_array() with an error from clEnqueueMapBuffer() of CL_INVALID_COMMAND_QUEUE.  I can get a model with the coco cfg file, however when testing it the results are incorrect (lots of high probability regions found that are of the wrong class and no detections with the correct class).  If I run the same on CUDA, it is working correctly.  This was done on both GeForce GT 730 and GTX 108 and an AMD GPU.  When reading through some of the allocation code it looks like some of the wrong array names were used.  Here are the changes I made.  Unfortunately they didn't fix my issue, but thought I'd pass them on in case they really are typos.
[diff.txt](https://github.com/sowson/darknet/files/2502249/diff.txt)

**Comment by sowson** [comment]
Thank you very much for the patch I have just applied it to my local repository and let me test it carefully and go back to you with results. I am using on macOS Mojave 10.14 and AMD 570 4GB eGPU. Thanks a lot!

**Comment by sowson** [comment]
OK, you may try it now by "git pull". Thanks!

**Comment by sowson** [comment]
I tested carefully and now a training should be fine from the memory management perspective. Please confirm and if it is true we may close this issue. Please keep in mind this post about NVIDIA GPUs and OpenCL https://devtalk.nvidia.com/default/topic/992502/why-is-cl_device_max_mem_alloc_size-never-larger-than-25-of-cl_device_global_mem_size-only-on-nvidia-/ With the NVIDIA GPU you may change in network cfg file one parameter from subdivisions=8 to subdivisions=16 that should solve the issue and use less memory by your GPU during the training. Thanks!

**Comment by sharived** [comment]
Thanks @sowson - Unfortunately I am still having issues.  I'm trying to train Yolov3 with VOC and getting a seg fault.  This seems to be happening prior to the next resize, so it is probably something different.  Could be my configs are wrong or something else with my data - I get the same crash if I run with CPU.  The good news is I haven't seen the original CL errors.  As I am currently not using CL for my training, I'm good with closing this issue.  Thanks!

**Comment by sowson** [comment]
Hi @sharived I found what was wrong and now I am testing on -gpus 0,1 on 2 TitanXp (no need to enable GPU_MULTI in Makefile) :D so far I got 2700 training steps on Yolo2 no errors, of course, it is on latest commit, enjoy! :D
